//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRegistry
    {
        public int ID { get; set; }
        public string firstName { get; set; }
        public string mInitial { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public int parishID { get; set; }
        public string community { get; set; }
        public string communityActivities { get; set; }
    
        public virtual difParish difParish { get; set; }
    }
}
