//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvotesEntities2 : DbContext
    {
        public EvotesEntities2()
            : base("name=EvotesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRegistry> CRegistries { get; set; }
        public virtual DbSet<difParish> difParishes { get; set; }
        public virtual DbSet<registryRecord> registryRecords { get; set; }
        public virtual DbSet<Ulogin> Ulogins { get; set; }
    }
}
